# Setup
title:               Jaekeun Lee's Space
tagline:             'a.k.a nowgeun'
description:         'A website of Jaekeun Lee for recording life and keeping track of studies, interests and experiences'
url:                 
baseurl:             ''
paginate:            5
future: true
plugins:
  - jekyll-sitemap

# Page
pages_list: 
  Projects: '/my-projects'
  About Me: '/about'
  Blog: '/blog'
  Writings: '/reviews'
  Contact: '/contact'
  Tags: '/tags'



# About/contact
author:
  name:              Jaekeun Lee
  url:               #
  email:             agdal1125@gmail.com

# Custom vars
version:             1.0.0
